# -*- coding: utf-8 -*-
"""fashion_product_image_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kk4H-fNW3H1ee7vof_WlYi3l4NBw68e9

# Fashion Product Image Classification
"""

# Import libraries
import kagglehub
import os
import pandas as pd
import numpy as np
from PIL import Image
from tensorflow.keras.preprocessing import image
from tensorflow.keras.utils import load_img, img_to_array
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import keras
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
from keras.layers import RandomFlip, RandomRotation, RandomZoom
from keras.callbacks import EarlyStopping
from keras.layers import SpatialDropout2D
import random
import numpy as np
import tensorflow as tf

random.seed(42)
np.random.seed(42)
tf.random.set_seed(42)

"""**Data Preprocessing**"""

kagglehub.login()

# Download latest version
path = kagglehub.dataset_download("paramaggarwal/fashion-product-images-small")

print("Path to dataset files:", path)

# List files in the downloaded path to identify the data file
print("Files in the dataset directory:")
for file in os.listdir(path):
    print(file)

# Construct the full path to the CSV file
csv_file_path = os.path.join(path, 'styles.csv')

# Load the CSV file into a pandas DataFrame, ignoring malformed rows
df = pd.read_csv(csv_file_path, on_bad_lines='skip')

# Construct the full path to the images directory
images_dir = os.path.join(path, 'images')

# Create a new column 'image_path' with the full path to each image
df['image_path'] = df['id'].apply(lambda x: os.path.join(images_dir, str(x) + '.jpg'))

# Filter out rows where the image file does not exist
initial_rows = len(df)
df = df[df['image_path'].apply(lambda x: os.path.exists(x))]
print(f"Removed {initial_rows - len(df)} rows where image files were not found.")

# Check for missing values in 'masterCategory' and drop them if any
if df['masterCategory'].isnull().any():
    initial_mc_rows = len(df)
    df.dropna(subset=['masterCategory'], inplace=True)
    print(f"Removed {initial_mc_rows - len(df)} rows with missing 'masterCategory'.")

# Display the updated DataFrame info and head to verify
print("\nDataFrame after mapping images and cleaning:\n")
print(df.info())
print('============================================================')
print(df.head())

# Display number of images in each category
category_counts = df['masterCategory'].value_counts()
category_counts

# Drop Personal Care, Free Items, Sporting Goods and Home categories because they don't have many images
df = df[df['masterCategory'] != 'Personal Care']
df = df[df['masterCategory'] != 'Free Items']
df = df[df['masterCategory'] != 'Sporting Goods']
df = df[df['masterCategory'] != 'Home']

#Display categories after dropping
category_counts = df['masterCategory'].value_counts()
category_counts

# Encode 'masterCategory' labels
le = LabelEncoder()
df['masterCategory_encoded'] = le.fit_transform(df['masterCategory'])

# Create subset with balanced classes
samples_per_class = 6600

balanced_df = df.groupby('masterCategory').apply(
    lambda x: x.sample(min(len(x), samples_per_class), random_state=42)
).reset_index(drop=True)

print("Samples per category after balancing:")
print(balanced_df['masterCategory'].value_counts())
print(f"\nTotal samples: {len(balanced_df)}")

X_balanced = balanced_df['image_path']
y_balanced = le.transform(balanced_df['masterCategory'])

# Split into train, validation, and test sets (70% train, 30% temp)
X_train, X_temp, y_train, y_temp = train_test_split(
    X_balanced, y_balanced,
    test_size=0.3,
    random_state=42,
    stratify=y_balanced
)

# Split X_temp into validation and test sets (15% val, 15% test)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp,
    test_size=0.5,
    random_state=42,
    stratify=y_temp
)

print(f"\nTraining set size: {len(X_train)} samples")
print(f"Validation set size: {len(X_val)} samples")
print(f"Test set size: {len(X_test)} samples")
print(f"Total samples in the final splits: {len(X_train) + len(X_val) + len(X_test)}")

# Show pixel value range
# Select a random image path from the DataFrame
random_image_path = df.sample(1)['image_path'].iloc[0]
img = image.load_img(random_image_path)
img_array = image.img_to_array(img)
print("Min pixel value:", np.min(img_array))
print("Max pixel value:", np.max(img_array))

# Resize and normalize images

image_size = (128, 128)
batch_size = 32

def preprocess_images(image_paths, labels, image_size):
    images = []
    for path in image_paths:
        img = load_img(path, target_size=image_size) # Resize images
        img_array = img_to_array(img) / 255.0  # Normalize pixel values
        images.append(img_array)
    return np.array(images), np.array(labels)

# Preprocess training, test and validation data
X_train_processed, y_train_processed = preprocess_images(X_train, y_train, image_size)
X_test_processed, y_test_processed = preprocess_images(X_test, y_test, image_size)
X_val_processed, y_val_processed = preprocess_images(X_val, y_val, image_size)

"""**Data Visualization**"""

# Display sample images
num_samples_to_display = 10
plt.figure(figsize=(15, 5))

samples = balanced_df.sample(num_samples_to_display)

for i, (idx, row) in enumerate(samples.iterrows()):
    try:
        # Load and show
        img = Image.open(row['image_path'])

        plt.subplot(1, num_samples_to_display, i + 1)
        plt.imshow(img)
        plt.title(row['masterCategory'], fontsize=10)
        plt.axis('off')
    except Exception as e:
        print(f"Could not load image at {row['image_path']}: {e}")

plt.tight_layout()
plt.show()

# Display class distribution
classes = balanced_df['masterCategory'].value_counts().index
counts = balanced_df['masterCategory'].value_counts().values

plt.figure(figsize=(10, 6))
plt.bar(classes, counts)
plt.title("Class Distribution of Master Categories")
plt.xlabel("Master Categories")
plt.ylabel("Number of Images")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

"""**Model Design**"""

model = Sequential([
    Conv2D(32, (3,3), activation='relu', padding='same', input_shape=(128,128,3)),
    BatchNormalization(),
    MaxPooling2D(2,2),
    Conv2D(64, (3,3), activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling2D(2,2),
    Conv2D(128, (3,3), activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling2D(2,2),
    Flatten(),
    Dense(256, activation='relu'),
    Dropout(0.5),
    Dense(len(le.classes_), activation='softmax')
])

# Display CNN layers
model.summary()

"""**Model Training**"""

# Compile model
model.compile(
    loss="sparse_categorical_crossentropy",
    optimizer="adam",
    metrics=["accuracy"],
)

# Train model
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

history = model.fit(
    X_train_processed, y_train_processed,
    validation_data=(X_val_processed, y_val_processed),
    epochs=30,
    batch_size=batch_size,
    callbacks=[early_stop]  # training stops when val_loss plateaus
  )

"""**Evaluation**"""

# Display accuracy
test_loss, test_acc = model.evaluate(X_test_processed, y_test_processed)
print("Test Accuracy:", test_acc)
print("Best Validation Accuracy:", max(history.history['val_accuracy']))

# Make predictions on the test set
y_pred_probs = model.predict(X_test_processed)
y_pred = np.argmax(y_pred_probs, axis=1)

# Display accuracy and loss
accuracy = history.history["accuracy"]
val_accuracy = history.history["val_accuracy"]
loss = history.history["loss"]
val_loss = history.history["val_loss"]
epochs = range(1, len(accuracy) + 1)

plt.plot(epochs, accuracy, "r--", label="Training accuracy")
plt.plot(epochs, val_accuracy, "b", label="Validation accuracy")
plt.title("Training and validation accuracy")
plt.legend()
plt.figure()

plt.plot(epochs, loss, "r--", label="Training loss")
plt.plot(epochs, val_loss, "b", label="Validation loss")
plt.title("Training and validation loss")
plt.legend()
plt.show()

# Compute confusion matrix
cm = confusion_matrix(y_test_processed, y_pred)

# Display confusion matrix
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=le.classes_)
disp.plot(cmap=plt.cm.Blues)
plt.title("Confusion Matrix")
plt.xticks(rotation=45, ha="right")
plt.show()

# Display predicted vs actual labels
samples_per_category = 3  # shows 3 examples per class

sample_indices = []
for class_idx in range(len(le.classes_)):
    class_indices = np.where(y_test_processed == class_idx)[0]
    sample_indices.extend(np.random.choice(class_indices, samples_per_category, replace=False))

predicted_labels = le.inverse_transform(np.argmax(y_pred_probs, axis=1))

for i in sample_indices:
    plt.imshow(X_test_processed[i])
    plt.title(f"Actual: {le.inverse_transform([y_test_processed[i]])[0]}, Predicted: {predicted_labels[i]}")
    plt.axis('off')
    plt.show()

"""**Improvement**"""

# Add data augmentation and lower dropout to 0.3
model_aug = Sequential([
    RandomFlip("horizontal"),
    RandomRotation(0.1),
    RandomZoom(0.1),
    Conv2D(32, (3,3), activation='relu', padding='same', input_shape=(128,128,3)),
    BatchNormalization(),
    MaxPooling2D(2,2),
    Conv2D(64, (3,3), activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling2D(2,2),
    Conv2D(128, (3,3), activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling2D(2,2),
    Flatten(),
    Dense(256, activation='relu'),
    Dropout(0.3),
    Dense(len(le.classes_), activation='softmax')
])

# Compile model
model_aug.compile(
    loss="sparse_categorical_crossentropy",
    optimizer="adam",
    metrics=["accuracy"],
)

# Train model
early_stop_aug = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

history_aug = model_aug.fit(
    X_train_processed, y_train_processed,
    validation_data=(X_val_processed, y_val_processed),
    epochs=30,
    batch_size=batch_size,
    callbacks=[early_stop_aug]
  )

# Display accuracy
test_loss, test_acc = model_aug.evaluate(X_test_processed, y_test_processed)
print("Test Accuracy:", test_acc)
print("Best Validation Accuracy:", max(history_aug.history['val_accuracy']))

# Add dropout
model_drop = Sequential([
  Conv2D(32, (3,3), activation='relu', padding='same', input_shape=(128,128,3)),
  BatchNormalization(),
  MaxPooling2D(2,2),
  SpatialDropout2D(0.1),   # drops entire feature maps
  Conv2D(64, (3,3), activation='relu', padding='same'),
  BatchNormalization(),
  MaxPooling2D(2,2),
  SpatialDropout2D(0.2),
  Conv2D(128, (3,3), activation='relu', padding='same'),
  BatchNormalization(),
  MaxPooling2D(2,2),
  SpatialDropout2D(0.3),   # increase rate as depth increases
  Flatten(),
  Dense(256, activation='relu'),
  Dropout(0.3),
  Dense(len(le.classes_), activation='softmax')
])

# Compile model
model_drop.compile(
    loss="sparse_categorical_crossentropy",
    optimizer="adam",
    metrics=["accuracy"],
)

# Train model
early_stop_drop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

history_drop = model_drop.fit(
    X_train_processed, y_train_processed,
    validation_data=(X_val_processed, y_val_processed),
    epochs=30,
    batch_size=batch_size,
    callbacks=[early_stop_drop]
  )

# Display accuracy
test_loss, test_acc = model_drop.evaluate(X_test_processed, y_test_processed)
print("Test Accuracy:", test_acc)
print("Best Validation Accuracy:", max(history_drop.history['val_accuracy']))

# Combine data augmentation and dropout
model_comb = Sequential([
  RandomFlip("horizontal"),
  RandomRotation(0.1),
  RandomZoom(0.1),
  Conv2D(32, (3,3), activation='relu', padding='same', input_shape=(128,128,3)),
  BatchNormalization(),
  MaxPooling2D(2,2),
  SpatialDropout2D(0.1),   # drops entire feature maps
  Conv2D(64, (3,3), activation='relu', padding='same'),
  BatchNormalization(),
  MaxPooling2D(2,2),
  SpatialDropout2D(0.2),
  Conv2D(128, (3,3), activation='relu', padding='same'),
  BatchNormalization(),
  MaxPooling2D(2,2),
  SpatialDropout2D(0.3),   # increase rate as depth increases
  Flatten(),
  Dense(256, activation='relu'),
  Dropout(0.3),
  Dense(len(le.classes_), activation='softmax')
])

# Compile model
model_comb.compile(
    loss="sparse_categorical_crossentropy",
    optimizer="adam",
    metrics=["accuracy"],
)

# Train model
early_stop_comb = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

history_comb = model_comb.fit(
    X_train_processed, y_train_processed,
    validation_data=(X_val_processed, y_val_processed),
    epochs=30,
    batch_size=batch_size,
    callbacks=[early_stop_comb]
  )

# Display accuracy
test_loss, test_acc = model_comb.evaluate(X_test_processed, y_test_processed)
print("Test Accuracy:", test_acc)
print("Best Validation Accuracy:", max(history_comb.history['val_accuracy']))

# Plot all val_accuracy curves together
plt.plot(history.history['val_accuracy'], label='Baseline')
plt.plot(history_aug.history['val_accuracy'], label='Augmentation')
plt.plot(history_drop.history['val_accuracy'], label='Dropout')
plt.plot(history_comb.history['val_accuracy'], label='Combined')
plt.title('Validation Accuracy Comparison')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

# Display accuracy, loss and confusion matrix for each model
def evaluate_model(model, history, name):
    # Make predictions
    y_pred_probs = model.predict(X_test_processed)
    y_pred = np.argmax(y_pred_probs, axis=1)

    # Accuracy and loss plots
    accuracy = history.history["accuracy"]
    val_accuracy = history.history["val_accuracy"]
    loss = history.history["loss"]
    val_loss = history.history["val_loss"]
    epochs = range(1, len(accuracy) + 1)

    plt.plot(epochs, accuracy, "r--", label="Training accuracy")
    plt.plot(epochs, val_accuracy, "b", label="Validation accuracy")
    plt.title(f"{name} - Training and Validation Accuracy")
    plt.legend()
    plt.figure()

    plt.plot(epochs, loss, "r--", label="Training loss")
    plt.plot(epochs, val_loss, "b", label="Validation loss")
    plt.title(f"{name} - Training and Validation Loss")
    plt.legend()
    plt.show()

    # Confusion matrix
    cm = confusion_matrix(y_test_processed, y_pred)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=le.classes_)
    disp.plot(cmap=plt.cm.Blues)
    plt.title(f"{name} - Confusion Matrix")
    plt.xticks(rotation=45, ha="right")
    plt.show()

# Call for each model
evaluate_model(model, history, "Baseline")
evaluate_model(model_aug, history_aug, "Augmentation")
evaluate_model(model_drop, history_drop, "Dropout")
evaluate_model(model_comb, history_comb, "Combined")

# Display gap in training accuracy and validation accuracy for each model
models = {
    'Baseline': history,
    'Augmentation': history_aug,
    'Dropout': history_drop,
    'Combined': history_comb
}

print(f"{'Model':<15} {'Train Acc':>10} {'Val Acc':>10} {'Gap':>10}")
print("-" * 50)
for name, hist in models.items():
    train_acc = max(hist.history['accuracy'])
    val_acc = max(hist.history['val_accuracy'])
    gap = train_acc - val_acc
    print(f"{name:<15} {train_acc:>10.4f} {val_acc:>10.4f} {gap:>10.4f}")

"""**Result Interpretation**

Key Takeaways
* The baseline model achieved excellent training accuracy with a slight gap between training accuracy and validation accuracy, indicating very slight overfitting.
* Adding augmentation to the baseline model achieved slightly lower accuracy than the baseline, and a slightly larger train-val gap indicating slight overfitting.
* Adding dropout only (without augmentation) to the baseline model achieved slightly lower accuracy than the baseline, and a slightly smallet train-val gap indicating very slight overfitting.
* The best performing model is the combination of augmentation and dropout. It has a great validation accuracy and a negative train-val gap indicating that the model generalizes well on the validation data and there is no overfitting. Tt is most balanced for accuracy without overfitting, and most effective at classifying fashion product images.
"""